defaults: &defaults
  update_supervisor_params:
    - supervisor
    - leader
  languages:
    en: "en"
    jp: "ja"
  tasks:
    statuses:
      new: 0
      in_progress: 1
      resolved: 2
      closed: 3
  flag_size: "20x15"
  image_user_size: "30x30"
  finish: "finish"
  finished: "finished"
  date_format: "%H:%M:%S %-d %B %Y"
  date_course_format: "%-d %B %Y"
  course_subject:
    finish: "finish"
    start: "progress"
  form:
    field_size: 50
  position:
    check_position: 0
    index: 1
  roles:
    trainer: "trainer"
    actions:
      - "create"
      - "read"
      - "update"
      - "destroy"
  hours_working_day: 8
  tabs:
    overview: "overview"
    subjects: "subjects"
    trainees: "trainees"
    trainers: "trainers"
development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults
