defaults: &defaults
  languages:
    en: "en"
    jp: "ja"
  flag_size: "20x15"
  finish: "finish"
  finished: "finished"
  date_format: "%H:%M:%S %-d %B %Y"
  course_subject:
    finish: "finish"
development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults
