defaults: &defaults
  update_supervisor_params:
    - supervisor
    - leader
  languages:
    en: "en"
    jp: "ja"
  flag_size: "20x15"
  image_user_size: "30x30"
  finish: "finish"
  finished: "finished"
  date_format: "%H:%M:%S %-d %B %Y"
  date_course_format: "%-d %B %Y"
  course_subject:
    finish: "finish"
    start: "progress"
  form:
    field_size: 50
  position:
    check_position: 0
    index: 1
development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults
